### PR TITLE
The Recipe App project completion

### PR DESCRIPTION
**Pull request by rtonata88**
In this PR we have created a recipe app that keeps track of recipes by different users. We have implemented the following features:

- List of public recipes
- Creating of new recipes
- List of foods
- Creation of food items
- Generating shopping list
- Linking food items to recipes
- Authentication system (Login, Register, forgot password, etc)
- Authorization system with `cancancan`

### CODE REVIEW

**Review by mmsesay — CHANGES_REQUESTED** [review]
Hi @rtonata88 & @oliverSCZ, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] I can see you have over 5000+ files . Please try to remove or gitignore irrelevant files.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmsesay** [comment]
- [ ] I got an error when I tried to start your project. Because of this reason, I was unable to verify your project UI and even check some functionality of your application. Please try to fix these issues so that the next reviewer can have access to your UI and test other parts of your project.

Please screenshot of the error I got.

Screenshot 1|
:----------------:|
a1


- [ ] Secondly, I noticed you wrote some tests. But unfortunately, when I ran them I got no example being picked up. Please see screenshot of the test

Screenshot 2 |
:-----------------:|
a2

**Comment by rtonata88** [comment]
> * [ ]  I got an error when I tried to start your project. Because of this reason, I was unable to verify your project UI and even check some functionality of your application. Please try to fix these issues so that the next reviewer can have access to your UI and test other parts of your project.
> 
> 
> Please screenshot of the error I got.
> Screenshot 1
> a1
> 
>     * [ ]  Secondly, I noticed you wrote some tests. But unfortunately, when I ran them I got no example being picked up. Please see screenshot of the test
> 
> 
> Screenshot 2
> a2

Hi, thank you for your review. We are unable to reproduce this error. Are you able to come on Slack for a quick chat?

**Review by BrianSammit — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hi @rtonata88 and @oliverSCZ , 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- Great job working on the design


Now you can merge this branch  :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by rukundoeric** [comment]
Hi @rtonata88 & @oliverSCZ,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------

**Pull request merged**
